### PR TITLE
Allow periods in display names

### PR DESCRIPTION
**Pull request by scottcrossen**
Great script! I noticed that one of my monitors doesn't get listed because the regex doesn't catch a period in the display name

### CODE REVIEW

**Comment by schlomo** [comment]
Thanks a lot! Good catch!

Could I kindly ask you to add your `xrandr` configuration as a test case so that future improvements won't break for your setup?

**Comment by scottcrossen** [comment]
Sure! Give me a few days (that computer isn't with me right now)

**Comment by scottcrossen** [comment]
Tests added. PTAL @schlomo

**Comment by schlomo** [comment]
Allow periods in display names, contributed by @scottcrossen ❤️

**Pull request merged**
